# Generated by Django 2.0.6 on 2018-12-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile', models.PositiveIntegerField(default='8554951545')),
                ('address', models.CharField(default='test', max_length=250)),
                ('type', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=500)),
                ('rc_path', models.CharField(max_length=500)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('has_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interface.Camera')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interface.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('fine_amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='vehicleviolation',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interface.Violation'),
        ),
    ]
